### ISSUE TITLE
[minor] ts-node not found

### ISSUE THREAD

**Issue by MeetM** [kdong007/sample-graphql#1]
Got the following error
```
[1] sh: ts-node: command not found
[1] [nodemon] failed to start process, "ts-node" exec not found
[1] [nodemon] Error
```

I installed it globally `npm install -g ts-node` to make it work. Should it be under devDependencies in package.json?

**Comment by kdong007** [comment]
yep. should have added that

**Comment by kdong007** [comment]
https://github.com/kdong007/sample-graphql/commit/e3fa7c15fe8e96ea130556945fd4ee0ff324a8b8
